/**
 * Demonstration Mock Data for CredentialVerify
 * ALL DATA IS FICTIONAL - Designed for Electoral Candidate Credential Verification Prototype
 */

import {
  Candidate,
  VerificationCase,
  SourceCheck,
  DiscrepancyItem,
  AuditLogEvent,
  UserAccount,
  SystemConfiguration,
  StatutoryRule,
  CandidateRFI,
} from '../types';

export const MOCK_USERS: UserAccount[] = [
  {
    id: 'usr_analyst_01',
    is_demo: true,
    name: 'Elena Vance',
    email: 'e.vance@elections.state.gov',
    staffId: 'STAFF-8842',
    role: 'VERIFICATION_ANALYST',
    jurisdiction: 'Pacifica National',
    mfaEnabled: true,
    lastLogin: '2026-08-26 09:14 UTC',
    accessReviewDate: '2026-11-15',
    status: 'ACTIVE',
  },
  {
    id: 'usr_adjudicator_01',
    is_demo: true,
    name: 'Marcus Chen',
    email: 'm.chen@elections.state.gov',
    staffId: 'STAFF-1092',
    role: 'SENIOR_ADJUDICATOR',
    jurisdiction: 'Pacifica National',
    mfaEnabled: true,
    lastLogin: '2026-08-26 08:30 UTC',
    accessReviewDate: '2026-12-01',
    status: 'ACTIVE',
  },
  {
    id: 'usr_intake_01',
    is_demo: true,
    name: 'Amina Osei',
    email: 'a.osei@elections.state.gov',
    staffId: 'STAFF-4419',
    role: 'INTAKE_OFFICER',
    jurisdiction: 'Pacifica National',
    mfaEnabled: true,
    lastLogin: '2026-08-26 10:02 UTC',
    accessReviewDate: '2026-10-30',
    status: 'ACTIVE',
  },
  {
    id: 'usr_admin_01',
    is_demo: true,
    name: 'David Sterling',
    email: 'd.sterling@elections.state.gov',
    staffId: 'STAFF-0012',
    role: 'ADMINISTRATOR',
    jurisdiction: 'Pacifica National',
    mfaEnabled: true,
    lastLogin: '2026-08-25 18:44 UTC',
    accessReviewDate: '2027-01-10',
    status: 'ACTIVE',
  },
  {
    id: 'usr_auditor_01',
    is_demo: true,
    name: 'Rachel Zimmerman',
    email: 'r.zimmerman@oversight.state.gov',
    staffId: 'AUDIT-7721',
    role: 'AUDITOR',
    jurisdiction: 'Pacifica National',
    mfaEnabled: true,
    lastLogin: '2026-08-26 07:11 UTC',
    accessReviewDate: '2026-12-31',
    status: 'ACTIVE',
  },
];

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: 'cand_001',
    is_demo: true,
    referenceCode: 'CAND-2026-0019',
    fullName: 'Dr. Arthur Sterling-Morales',
    otherNames: 'Arthur S. Morales',
    dateOfBirth: '1974-03-15',
    electionId: 'elec_2026_nat',
    electionName: '2026 Pacifica National Assembly',
    officeContested: 'Member of Parliament - Constituency 4 (Metropolis)',
    jurisdiction: 'Pacifica National',
    contactEmail: 'a.sterling.campaign@pacificamail.org',
    contactPhone: '+1 (555) 019-2831',
    submissionDate: '2026-08-22 14:30',
    status: 'NEEDS_REVIEW',
    completenessScore: 100,
    assignedReviewerId: 'usr_analyst_01',
    assignedReviewerName: 'Elena Vance',
    lastUpdated: '2026-08-26 11:20',
    documents: [
      {
        id: 'doc_001_deg',
    is_demo: true,
        candidateId: 'cand_001',
        credentialType: 'ACADEMIC_DEGREE',
        credentialTitle: 'Doctor of Jurisprudence (JD) Degree Certificate',
        fileName: 'Sterling_Doctor_Jurisprudence_VeritasiaUniv.pdf',
        fileSizeBytes: 2420000,
        uploadTimestamp: '2026-08-22 14:31',
        mimeType: 'application/pdf',
        totalPages: 2,
        status: 'NEEDS_REVIEW',
        vectorDocType: 'DEGREE',
        qualityWarnings: [
          {
            type: 'PARTIAL_TRUNCATION',
            message: 'Lower registrar embossing seal is faint; manual contrast review recommended',
            severity: 'WARNING',
          },
        ],
        extractedFields: [
          {
            id: 'fld_deg_01',
    is_demo: true,
            fieldKey: 'conferral_institution',
            fieldName: 'Conferring Institution',
            originalValue: 'Veritasia State University School of Law',
            normalizedValue: 'VERITASIA STATE UNIVERSITY - SCHOOL OF LAW',
            isCorrected: false,
            extractionConfidence: 99,
            status: 'VERIFIED',
            evidencePage: 1,
            evidenceRegion: { page: 1, x: 15, y: 18, width: 70, height: 8, label: 'Institution Header' },
            sourceStatus: 'MATCHED',
            verifiedAgainstSource: 'National Academic Degree Clearinghouse (NADC)',
          },
          {
            id: 'fld_deg_02',
    is_demo: true,
            fieldKey: 'degree_title',
            fieldName: 'Conferred Degree',
            originalValue: 'Doctor of Jurisprudence',
            normalizedValue: 'DOCTOR OF JURISPRUDENCE (JD)',
            isCorrected: false,
            extractionConfidence: 98,
            status: 'VERIFIED',
            evidencePage: 1,
            evidenceRegion: { page: 1, x: 20, y: 38, width: 60, height: 7, label: 'Degree Conferral Statement' },
            sourceStatus: 'MATCHED',
            verifiedAgainstSource: 'National Academic Degree Clearinghouse (NADC)',
          },
          {
            id: 'fld_deg_03',
    is_demo: true,
            fieldKey: 'conferral_date',
            fieldName: 'Date of Conferral',
            originalValue: 'May 18, 2002',
            normalizedValue: '2002-05-18',
            correctedValue: '2002-06-12',
            isCorrected: true,
            correctionReasonCode: 'REGISTRAR_RECORDS_AMENDMENT',
            correctionReasonNote: 'Official registrar records indicate formal convocation was June 12, 2002; degree text lists term close date.',
            reviewerNote: 'Field corrected pursuant to authoritative clearinghouse transcript response.',
            extractionConfidence: 95,
            status: 'NEEDS_REVIEW',
            evidencePage: 1,
            evidenceRegion: { page: 1, x: 25, y: 55, width: 50, height: 6, label: 'Conferral Date Line' },
            sourceStatus: 'MISMATCH',
            verifiedAgainstSource: 'National Academic Degree Clearinghouse (NADC)',
          },
          {
            id: 'fld_deg_04',
    is_demo: true,
            fieldKey: 'student_identifier',
            fieldName: 'Registration / Student Index',
            originalValue: 'VSU-LAW-1999-0482',
            normalizedValue: 'VSU-LAW-1999-0482',
            isCorrected: false,
            extractionConfidence: 97,
            status: 'VERIFIED',
            evidencePage: 1,
            evidenceRegion: { page: 1, x: 70, y: 88, width: 25, height: 5, label: 'Archival Registry Number' },
            sourceStatus: 'MATCHED',
            verifiedAgainstSource: 'Veritasia State Higher Ed Board',
          },
        ],
      },
      {
        id: 'doc_001_bar',
    is_demo: true,
        candidateId: 'cand_001',
        credentialType: 'PROFESSIONAL_LICENSE',
        credentialTitle: 'Bar Council Certificate of Good Standing',
        fileName: 'Sterling_Bar_Good_Standing_2026.pdf',
        fileSizeBytes: 1540000,
        uploadTimestamp: '2026-08-22 14:32',
        mimeType: 'application/pdf',
        totalPages: 1,
        status: 'VERIFIED',
        vectorDocType: 'BAR_LICENSE',
        qualityWarnings: [],
        extractedFields: [
          {
            id: 'fld_bar_01',
    is_demo: true,
            fieldKey: 'license_jurisdiction',
            fieldName: 'Licensing Authority',
            originalValue: 'Supreme Judicial Bar of the Province of Pacifica',
            normalizedValue: 'SUPREME JUDICIAL BAR OF PACIFICA',
            isCorrected: false,
            extractionConfidence: 99,
            status: 'VERIFIED',
            evidencePage: 1,
            evidenceRegion: { page: 1, x: 10, y: 15, width: 80, height: 10, label: 'Bar Header & Seal' },
            sourceStatus: 'MATCHED',
            verifiedAgainstSource: 'Pacifica Bar Association Live Registry',
          },
          {
            id: 'fld_bar_02',
    is_demo: true,
            fieldKey: 'license_status',
            fieldName: 'Standing & Ethical Status',
            originalValue: 'Active - In Good Standing (No Sanctions)',
            normalizedValue: 'ACTIVE_GOOD_STANDING',
            isCorrected: false,
            extractionConfidence: 98,
            status: 'VERIFIED',
            evidencePage: 1,
            evidenceRegion: { page: 1, x: 15, y: 62, width: 70, height: 8, label: 'Standing Certification Clause' },
            sourceStatus: 'MATCHED',
            verifiedAgainstSource: 'Pacifica Bar Association Live Registry',
          },
          {
            id: 'fld_bar_03',
    is_demo: true,
            fieldKey: 'license_number',
            fieldName: 'Roll of Advocates Number',
            originalValue: 'BAR-PAC-2003-8819',
            normalizedValue: 'BAR-PAC-2003-8819',
            isCorrected: false,
            extractionConfidence: 100,
            status: 'VERIFIED',
            evidencePage: 1,
            evidenceRegion: { page: 1, x: 25, y: 45, width: 50, height: 6, label: 'Advocate Roll Identifier' },
            sourceStatus: 'MATCHED',
            verifiedAgainstSource: 'Pacifica Bar Association Live Registry',
          },
        ],
      },
      {
        id: 'doc_001_cit',
    is_demo: true,
        candidateId: 'cand_001',
        credentialType: 'CITIZENSHIP',
        credentialTitle: 'Statutory Birth Certificate & Citizenship Register',
        fileName: 'Sterling_Citizenship_Registration.pdf',
        fileSizeBytes: 3100000,
        uploadTimestamp: '2026-08-22 14:30',
        mimeType: 'application/pdf',
        totalPages: 1,
        status: 'VERIFIED',
        vectorDocType: 'CITIZENSHIP_CERT',
        qualityWarnings: [],
        extractedFields: [
          {
            id: 'fld_cit_01',
    is_demo: true,
            fieldKey: 'citizen_status',
            fieldName: 'Citizenship Category',
            originalValue: 'Citizen by Birth (Statutory Clause 12-A)',
            normalizedValue: 'CITIZEN_BY_BIRTH',
            isCorrected: false,
            extractionConfidence: 99,
            status: 'VERIFIED',
            evidencePage: 1,
            evidenceRegion: { page: 1, x: 10, y: 35, width: 80, height: 8, label: 'Statutory Citizenship Designation' },
            sourceStatus: 'MATCHED',
            verifiedAgainstSource: 'National Registry of Civil Status (NRCS)',
          },
        ],
      },
    ],
  },
  {
    id: 'cand_002',
    is_demo: true,
    referenceCode: 'CAND-2026-0042',
    fullName: 'Hon. Beatrice Nadia Kalu',
    otherNames: 'Beatrice N. Kalu-Svensson',
    dateOfBirth: '1981-11-09',
    electionId: 'elec_2026_gov',
    electionName: '2026 Capital Territory Gubernatorial',
    officeContested: 'Governor of Capital Territory',
    jurisdiction: 'Pacifica National',
    contactEmail: 'kalu.gubernatorial@electionfocus.net',
    contactPhone: '+1 (555) 012-9944',
    submissionDate: '2026-08-23 09:15',
    status: 'INFO_REQUIRED',
    completenessScore: 80,
    assignedReviewerId: 'usr_analyst_01',
    assignedReviewerName: 'Elena Vance',
    lastUpdated: '2026-08-26 10:05',
    documents: [
      {
        id: 'doc_002_fin',
    is_demo: true,
        candidateId: 'cand_002',
        credentialType: 'FINANCIAL_DISCLOSURE',
        credentialTitle: 'Public Integrity Asset & Liability Statement 2025-2026',
        fileName: 'Kalu_Financial_Disclosure_Schedule_A_B.pdf',
        fileSizeBytes: 4800000,
        uploadTimestamp: '2026-08-23 09:16',
        mimeType: 'application/pdf',
        totalPages: 4,
        status: 'INFO_REQUIRED',
        vectorDocType: 'TAX_DISCLOSURE',
        qualityWarnings: [
          {
            type: 'PARTIAL_TRUNCATION',
            message: 'Schedule D (Real Property Beneficial Ownership) is referenced on page 2 but missing in filing attachment.',
            severity: 'CRITICAL',
          },
        ],
        extractedFields: [
          {
            id: 'fld_fin_01',
    is_demo: true,
            fieldKey: 'filing_period',
            fieldName: 'Statutory Tax & Disclosure Period',
            originalValue: 'Fiscal Years 2024 & 2025',
            normalizedValue: '2024-2025',
            isCorrected: false,
            extractionConfidence: 98,
            status: 'VERIFIED',
            evidencePage: 1,
            evidenceRegion: { page: 1, x: 20, y: 22, width: 60, height: 6, label: 'Tax Year Scope' },
            sourceStatus: 'MATCHED',
            verifiedAgainstSource: 'Department of Revenue Ethics Gateway',
          },
          {
            id: 'fld_fin_02',
    is_demo: true,
            fieldKey: 'schedule_d_status',
            fieldName: 'Schedule D Annexure Completeness',
            originalValue: '[Omitted in submitted packet]',
            normalizedValue: 'MISSING_MANDATORY_ANNEXURE',
            isCorrected: false,
            extractionConfidence: 94,
            status: 'INFO_REQUIRED',
            evidencePage: 2,
            evidenceRegion: { page: 2, x: 15, y: 70, width: 70, height: 8, label: 'Annexure Cross-Reference Line' },
            sourceStatus: 'SOURCE_UNAVAILABLE',
            reviewerNote: 'Formal Information Request #IR-2026-88 sent to candidate representative for missing Schedule D.',
          },
        ],
      },
    ],
  },
  {
    id: 'cand_003',
    is_demo: true,
    referenceCode: 'CAND-2026-0081',
    fullName: 'Julian Robert Hawthorne',
    otherNames: 'J. R. Hawthorne',
    dateOfBirth: '1969-07-24',
    electionId: 'elec_2026_jud',
    electionName: '2026 Western Province Judicial Council',
    officeContested: 'Appellate Division Judge - Seat 3',
    jurisdiction: 'Pacifica National',
    contactEmail: 'hawthorne.judicial@legalchamber.org',
    contactPhone: '+1 (555) 018-4421',
    submissionDate: '2026-08-20 16:45',
    status: 'CONTRADICTED',
    completenessScore: 100,
    assignedReviewerId: 'usr_adjudicator_01',
    assignedReviewerName: 'Marcus Chen',
    lastUpdated: '2026-08-26 08:50',
    documents: [
      {
        id: 'doc_003_bar',
    is_demo: true,
        candidateId: 'cand_003',
        credentialType: 'PROFESSIONAL_LICENSE',
        credentialTitle: 'Bar Council Attestation of Continuous 15-Year Practice',
        fileName: 'Hawthorne_Judicial_Bar_Attestation.pdf',
        fileSizeBytes: 2100000,
        uploadTimestamp: '2026-08-20 16:46',
        mimeType: 'application/pdf',
        totalPages: 2,
        status: 'CONTRADICTED',
        vectorDocType: 'BAR_LICENSE',
        qualityWarnings: [],
        extractedFields: [
          {
            id: 'fld_hwt_01',
    is_demo: true,
            fieldKey: 'continuous_years_practice',
            fieldName: 'Claimed Continuous Practice Duration',
            originalValue: '18 Years (Admitted Oct 2007, Unbroken)',
            normalizedValue: '18_YEARS_CONTINUOUS',
            isCorrected: false,
            extractionConfidence: 97,
            status: 'CONTRADICTED',
            evidencePage: 1,
            evidenceRegion: { page: 1, x: 15, y: 42, width: 70, height: 8, label: 'Continuous Practice Statement' },
            sourceStatus: 'MISMATCH',
            verifiedAgainstSource: 'Bar Disciplinary & Administrative Council Register',
            reviewerNote: 'Discrepancy: Authoritative Bar Council register reflects voluntary administrative inactive leave between March 2014 and June 2016 (27 months). Potential integrity concern regarding continuous qualification clause.',
          },
        ],
      },
    ],
  },
  {
    id: 'cand_004',
    is_demo: true,
    referenceCode: 'CAND-2026-0104',
    fullName: 'Senator Fatima Zahra Al-Mansoor',
    otherNames: '',
    dateOfBirth: '1978-12-04',
    electionId: 'elec_2026_nat',
    electionName: '2026 Pacifica National Assembly',
    officeContested: 'Senator - Regional At-Large Seat',
    jurisdiction: 'Pacifica National',
    contactEmail: 'f.almansoor@senate-pacifica.org',
    contactPhone: '+1 (555) 014-3329',
    submissionDate: '2026-08-24 11:00',
    status: 'VERIFIED',
    completenessScore: 100,
    assignedReviewerId: 'usr_analyst_01',
    assignedReviewerName: 'Elena Vance',
    lastUpdated: '2026-08-25 17:15',
    documents: [],
  },
  {
    id: 'cand_005',
    is_demo: true,
    referenceCode: 'CAND-2026-0118',
    fullName: 'Engr. Gabriel Thomas Vance',
    otherNames: 'G. T. Vance',
    dateOfBirth: '1985-05-22',
    electionId: 'elec_2026_nat',
    electionName: '2026 Pacifica National Assembly',
    officeContested: 'Member of Parliament - Constituency 9',
    jurisdiction: 'Pacifica National',
    contactEmail: 'vance.campaign2026@mailwest.com',
    contactPhone: '+1 (555) 011-5582',
    submissionDate: '2026-08-25 08:30',
    status: 'PENDING',
    completenessScore: 100,
    assignedReviewerId: 'usr_analyst_01',
    assignedReviewerName: 'Elena Vance',
    lastUpdated: '2026-08-26 09:00',
    documents: [],
  },
  {
    id: 'cand_006',
    is_demo: true,
    referenceCode: 'CAND-2026-0133',
    fullName: 'Prof. Miriam Shoshana Goldstein',
    otherNames: 'Miriam S. Goldstein',
    dateOfBirth: '1965-09-17',
    electionId: 'elec_2026_gov',
    electionName: '2026 Capital Territory Gubernatorial',
    officeContested: 'Lieutenant Governor of Capital Territory',
    jurisdiction: 'Pacifica National',
    contactEmail: 'goldstein.office@capitolcivic.org',
    contactPhone: '+1 (555) 017-7721',
    submissionDate: '2026-08-21 13:20',
    status: 'RESTRICTED',
    completenessScore: 100,
    assignedReviewerId: 'usr_adjudicator_01',
    assignedReviewerName: 'Marcus Chen',
    lastUpdated: '2026-08-26 07:45',
    documents: [],
  },
  {
    id: 'cand_007',
    is_demo: true,
    referenceCode: 'CAND-2026-0155',
    fullName: 'Councilor Tariq Kwame Mensah',
    otherNames: 'T. K. Mensah',
    dateOfBirth: '1982-01-30',
    electionId: 'elec_2026_nat',
    electionName: '2026 Pacifica National Assembly',
    officeContested: 'Member of Parliament - Constituency 2',
    jurisdiction: 'Pacifica National',
    contactEmail: 'mensah.constituency2@westmail.net',
    contactPhone: '+1 (555) 019-3388',
    submissionDate: '2026-08-23 15:40',
    status: 'VERIFIED',
    completenessScore: 100,
    assignedReviewerId: 'usr_analyst_01',
    assignedReviewerName: 'Elena Vance',
    lastUpdated: '2026-08-25 16:30',
    documents: [],
  },
  {
    id: 'cand_008',
    is_demo: true,
    referenceCode: 'CAND-2026-0172',
    fullName: 'Adelaide Charlotte Dubois',
    otherNames: 'A. C. Dubois-Lambert',
    dateOfBirth: '1988-06-14',
    electionId: 'elec_2026_gov',
    electionName: '2026 Capital Territory Gubernatorial',
    officeContested: 'Governor of Capital Territory',
    jurisdiction: 'Pacifica National',
    contactEmail: 'dubois.lead@pacificaforward.org',
    contactPhone: '+1 (555) 013-4490',
    submissionDate: '2026-08-24 14:10',
    status: 'NEEDS_REVIEW',
    completenessScore: 90,
    assignedReviewerId: 'usr_analyst_01',
    assignedReviewerName: 'Elena Vance',
    lastUpdated: '2026-08-26 11:00',
    documents: [],
  },
  {
    id: 'cand_009',
    is_demo: true,
    referenceCode: 'CAND-2026-0190',
    fullName: 'Hon. Sanjay Devendra Patel',
    otherNames: 'S. D. Patel',
    dateOfBirth: '1971-10-03',
    electionId: 'elec_2026_jud',
    electionName: '2026 Western Province Judicial Council',
    officeContested: 'Commercial & Arbitration Division Judge',
    jurisdiction: 'Pacifica National',
    contactEmail: 'patel.chambers@pacificajustice.org',
    contactPhone: '+1 (555) 016-8833',
    submissionDate: '2026-08-19 11:25',
    status: 'VERIFIED',
    completenessScore: 100,
    assignedReviewerId: 'usr_adjudicator_01',
    assignedReviewerName: 'Marcus Chen',
    lastUpdated: '2026-08-24 14:00',
    documents: [],
  },
  {
    id: 'cand_010',
    is_demo: true,
    referenceCode: 'CAND-2026-0204',
    fullName: 'Major Lucas Sean Brennan (Ret.)',
    otherNames: 'L. S. Brennan',
    dateOfBirth: '1976-04-18',
    electionId: 'elec_2026_nat',
    electionName: '2026 Pacifica National Assembly',
    officeContested: 'Member of Parliament - Constituency 11',
    jurisdiction: 'Pacifica National',
    contactEmail: 'brennan.defence@veteranscoalition.org',
    contactPhone: '+1 (555) 015-6677',
    submissionDate: '2026-08-25 16:00',
    status: 'PENDING',
    completenessScore: 100,
    assignedReviewerId: 'usr_analyst_01',
    assignedReviewerName: 'Elena Vance',
    lastUpdated: '2026-08-26 09:30',
    documents: [],
  },
  {
    id: 'cand_011',
    is_demo: true,
    referenceCode: 'CAND-2026-0222',
    fullName: 'Dr. Evelyn Yael Rostova',
    otherNames: 'Evelyn Rostova-Kim',
    dateOfBirth: '1983-08-12',
    electionId: 'elec_2026_gov',
    electionName: '2026 Capital Territory Gubernatorial',
    officeContested: 'Lieutenant Governor of Capital Territory',
    jurisdiction: 'Pacifica National',
    contactEmail: 'rostova.policy@civicleadership.edu',
    contactPhone: '+1 (555) 012-7711',
    submissionDate: '2026-08-22 17:30',
    status: 'VERIFIED',
    completenessScore: 100,
    assignedReviewerId: 'usr_analyst_01',
    assignedReviewerName: 'Elena Vance',
    lastUpdated: '2026-08-25 15:00',
    documents: [],
  },
  {
    id: 'cand_012',
    is_demo: true,
    referenceCode: 'CAND-2026-0240',
    fullName: 'Clara Maria Villanueva-Cruz',
    otherNames: 'Clara M. Villanueva',
    dateOfBirth: '1990-02-28',
    electionId: 'elec_2026_nat',
    electionName: '2026 Pacifica National Assembly',
    officeContested: 'Member of Parliament - Constituency 7',
    jurisdiction: 'Pacifica National',
    contactEmail: 'villanueva.clara@communitypulse.org',
    contactPhone: '+1 (555) 017-9922',
    submissionDate: '2026-08-26 08:00',
    status: 'PENDING',
    completenessScore: 85,
    assignedReviewerId: 'usr_intake_01',
    assignedReviewerName: 'Amina Osei',
    lastUpdated: '2026-08-26 08:30',
    documents: [],
  },
];

export const INITIAL_CASES: VerificationCase[] = [
  {
    id: 'case_001',
    is_demo: true,
    caseReference: 'CASE-2026-0019-JD',
    candidateId: 'cand_001',
    candidateName: 'Dr. Arthur Sterling-Morales',
    electionName: '2026 Pacifica National Assembly',
    officeContested: 'Member of Parliament - Constituency 4',
    jurisdiction: 'Pacifica National',
    workflowStatus: 'NEEDS_REVIEW',
    stage: 'DISCREPANCY_REVIEW',
    priority: 'HIGH',
    assignedReviewerId: 'usr_analyst_01',
    assignedReviewerName: 'Elena Vance',
    submissionDate: '2026-08-22 14:30',
    slaDeadline: '2026-08-27 17:00',
    ageHours: 92,
    reasonForReview: 'Academic degree conferral date mismatch against National Academic Clearinghouse; registrar correction applied.',
    documentsCount: 3,
    claimsCount: 8,
    sourceChecksCount: 4,
    discrepanciesCount: 1,
    openItemsCount: 1,
  },
  {
    id: 'case_002',
    is_demo: true,
    caseReference: 'CASE-2026-0042-FD',
    candidateId: 'cand_002',
    candidateName: 'Hon. Beatrice Nadia Kalu',
    electionName: '2026 Capital Territory Gubernatorial',
    officeContested: 'Governor of Capital Territory',
    jurisdiction: 'Pacifica National',
    workflowStatus: 'INFO_REQUIRED',
    stage: 'INTAKE',
    priority: 'URGENT',
    assignedReviewerId: 'usr_analyst_01',
    assignedReviewerName: 'Elena Vance',
    submissionDate: '2026-08-23 09:15',
    slaDeadline: '2026-08-26 23:59',
    ageHours: 74,
    reasonForReview: 'Missing Schedule D (Real Property Beneficial Disclosures). Formal information request outstanding.',
    documentsCount: 2,
    claimsCount: 6,
    sourceChecksCount: 2,
    discrepanciesCount: 0,
    openItemsCount: 1,
  },
  {
    id: 'case_003',
    is_demo: true,
    caseReference: 'CASE-2026-0081-JC',
    candidateId: 'cand_003',
    candidateName: 'Julian Robert Hawthorne',
    electionName: '2026 Western Province Judicial Council',
    officeContested: 'Appellate Division Judge - Seat 3',
    jurisdiction: 'Pacifica National',
    workflowStatus: 'CONTRADICTED',
    stage: 'ADJUDICATION',
    priority: 'URGENT',
    assignedReviewerId: 'usr_adjudicator_01',
    assignedReviewerName: 'Marcus Chen',
    submissionDate: '2026-08-20 16:45',
    slaDeadline: '2026-08-26 18:00',
    ageHours: 140,
    reasonForReview: 'Statutory 15-year continuous practice claim contradicted by 27-month inactive administrative bar record.',
    documentsCount: 4,
    claimsCount: 12,
    sourceChecksCount: 5,
    discrepanciesCount: 2,
    openItemsCount: 2,
  },
  {
    id: 'case_004',
    is_demo: true,
    caseReference: 'CASE-2026-0104-NA',
    candidateId: 'cand_004',
    candidateName: 'Senator Fatima Zahra Al-Mansoor',
    electionName: '2026 Pacifica National Assembly',
    officeContested: 'Senator - Regional At-Large Seat',
    jurisdiction: 'Pacifica National',
    workflowStatus: 'VERIFIED',
    stage: 'COMPLETED',
    priority: 'STANDARD',
    assignedReviewerId: 'usr_analyst_01',
    assignedReviewerName: 'Elena Vance',
    submissionDate: '2026-08-24 11:00',
    slaDeadline: '2026-08-29 17:00',
    ageHours: 48,
    reasonForReview: 'Routine credential verification; all primary sources confirmed.',
    documentsCount: 3,
    claimsCount: 9,
    sourceChecksCount: 4,
    discrepanciesCount: 0,
    openItemsCount: 0,
    recommendation: {
      recommendationType: 'REQUIREMENTS_SATISFIED',
      reasonCodes: ['ALL_PRIMARY_SOURCES_MATCHED', 'MANDATORY_CRITERIA_VERIFIED'],
      rationale: 'All statutory identity, citizenship, and academic prerequisites independently corroborated by Tier 1 registries.',
      submittedBy: 'Elena Vance',
      submittedTimestamp: '2026-08-25 17:15',
      confirmedClaimsCount: 9,
      contradictedClaimsCount: 0,
      openRisks: [],
      isFinalAdverseDecision: false,
      finalAdjudicatorSignoff: 'Marcus Chen (Senior Adjudicator)',
    },
  },
  {
    id: 'case_005',
    is_demo: true,
    caseReference: 'CASE-2026-0118-MP',
    candidateId: 'cand_005',
    candidateName: 'Engr. Gabriel Thomas Vance',
    electionName: '2026 Pacifica National Assembly',
    officeContested: 'Member of Parliament - Constituency 9',
    jurisdiction: 'Pacifica National',
    workflowStatus: 'PENDING',
    stage: 'SOURCE_CHECK',
    priority: 'MEDIUM',
    assignedReviewerId: 'usr_analyst_01',
    assignedReviewerName: 'Elena Vance',
    submissionDate: '2026-08-25 08:30',
    slaDeadline: '2026-08-30 17:00',
    ageHours: 26,
    reasonForReview: 'Pending asynchronous response from National Civil Aviation & Engineering Licensure Board.',
    documentsCount: 3,
    claimsCount: 7,
    sourceChecksCount: 3,
    discrepanciesCount: 0,
    openItemsCount: 1,
  },
  {
    id: 'case_006',
    is_demo: true,
    caseReference: 'CASE-2026-0133-LG',
    candidateId: 'cand_006',
    candidateName: 'Prof. Miriam Shoshana Goldstein',
    electionName: '2026 Capital Territory Gubernatorial',
    officeContested: 'Lieutenant Governor of Capital Territory',
    jurisdiction: 'Pacifica National',
    workflowStatus: 'RESTRICTED',
    stage: 'ADJUDICATION',
    priority: 'HIGH',
    assignedReviewerId: 'usr_adjudicator_01',
    assignedReviewerName: 'Marcus Chen',
    submissionDate: '2026-08-21 13:20',
    slaDeadline: '2026-08-27 12:00',
    ageHours: 118,
    reasonForReview: 'Escalated to restricted senior review queue due to dual-nationality statutory interpretation question.',
    documentsCount: 5,
    claimsCount: 14,
    sourceChecksCount: 6,
    discrepanciesCount: 1,
    openItemsCount: 2,
  },
];

export const MOCK_SOURCE_CHECKS: SourceCheck[] = [
  {
    id: 'src_001',
    is_demo: true,
    caseId: 'case_001',
    authorityName: 'National Academic Degree Clearinghouse (NADC)',
    credentialType: 'ACADEMIC_DEGREE',
    checkedTimestamp: '2026-08-26 09:15 UTC',
    responseTimeMs: 342,
    resultStatus: 'VERIFIED',
    reliabilityTier: 'TIER_1_STATUTORY_AUTHORITY',
    connectorStatus: 'HEALTHY',
    evidenceReference: 'NADC-TRX-2026-881920',
    responsePayloadSummary: 'Matched Student ID VSU-LAW-1999-0482. Degree JD conferred 2002-06-12.',
  },
  {
    id: 'src_002',
    is_demo: true,
    caseId: 'case_001',
    authorityName: 'Supreme Judicial Bar of Pacifica Registry API',
    credentialType: 'PROFESSIONAL_LICENSE',
    checkedTimestamp: '2026-08-26 09:16 UTC',
    responseTimeMs: 210,
    resultStatus: 'VERIFIED',
    reliabilityTier: 'TIER_1_STATUTORY_AUTHORITY',
    connectorStatus: 'HEALTHY',
    evidenceReference: 'BAR-PAC-API-VER-904',
    responsePayloadSummary: 'Roll #BAR-PAC-2003-8819. Current status: Active in good standing. Zero sanctions on record.',
  },
  {
    id: 'src_003',
    is_demo: true,
    caseId: 'case_001',
    authorityName: 'National Registry of Civil Status (NRCS)',
    credentialType: 'CITIZENSHIP',
    checkedTimestamp: '2026-08-26 09:16 UTC',
    responseTimeMs: 185,
    resultStatus: 'VERIFIED',
    reliabilityTier: 'TIER_1_STATUTORY_AUTHORITY',
    connectorStatus: 'HEALTHY',
    evidenceReference: 'NRCS-CIV-2026-0044',
    responsePayloadSummary: 'Birth Registration verified. Pacifica Citizen by birth.',
  },
  {
    id: 'src_004',
    is_demo: true,
    caseId: 'case_002',
    authorityName: 'National Archive Gateway & Identity Service',
    credentialType: 'CITIZENSHIP',
    checkedTimestamp: '2026-08-26 08:30 UTC',
    responseTimeMs: 8200,
    resultStatus: 'RATE_LIMITED',
    reliabilityTier: 'TIER_2_OFFICIAL_REGISTRY',
    connectorStatus: 'DEGRADED',
    evidenceReference: 'NAG-ERR-429-THROTTLE',
    responsePayloadSummary: 'Connector returned HTTP 429 Too Many Requests. Statutory batch limit reached.',
  },
  {
    id: 'src_005',
    is_demo: true,
    caseId: 'case_002',
    authorityName: 'Department of Revenue Ethics & Financial Disclosure Gateway',
    credentialType: 'FINANCIAL_DISCLOSURE',
    checkedTimestamp: '2026-08-26 08:45 UTC',
    responseTimeMs: 12000,
    resultStatus: 'UNAVAILABLE',
    reliabilityTier: 'TIER_1_STATUTORY_AUTHORITY',
    connectorStatus: 'OFFLINE',
    evidenceReference: 'REV-ERR-503-TIMEOUT',
    responsePayloadSummary: 'Upstream gateway socket timeout (503 Service Unavailable). Retry scheduled.',
  },
  {
    id: 'src_006',
    is_demo: true,
    caseId: 'case_003',
    authorityName: 'Western Province High Court Registry',
    credentialType: 'PROFESSIONAL_LICENSE',
    checkedTimestamp: '2026-08-26 07:20 UTC',
    responseTimeMs: 410,
    resultStatus: 'VERIFIED',
    reliabilityTier: 'TIER_1_STATUTORY_AUTHORITY',
    connectorStatus: 'HEALTHY',
    evidenceReference: 'WPHC-REG-2026-773',
    responsePayloadSummary: 'Continuous practice clause contradicted: Inactive registry status 2014-03-01 to 2016-06-15.',
  },
];

export const MOCK_DISCREPANCIES: DiscrepancyItem[] = [
  {
    id: 'disc_001',
    is_demo: true,
    caseId: 'case_001',
    claimType: 'Academic Degree Conferral Date',
    fieldLabel: 'Conferral Date',
    candidateDocumentValue: 'May 18, 2002 (Spring Semester Close)',
    authoritativeSourceValue: 'June 12, 2002 (Official Board Convocation)',
    sourceName: 'National Academic Degree Clearinghouse (NADC)',
    evidenceLocation: 'Page 1, Paragraph 2 & Registrar Seal',
    dateChecked: '2026-08-26 09:15 UTC',
    reliabilityTier: 'TIER_1_STATUTORY_AUTHORITY',
    status: 'SUPPORTED',
    resolution: 'ACCEPTED_SOURCE',
    resolutionNote: 'Discrepancy explained: Academic calendar lists last exam day, whereas formal degree conferral occurred at June convocation. Claim substantiated.',
    resolvedBy: 'Elena Vance (Verification Analyst)',
  },
  {
    id: 'disc_002',
    is_demo: true,
    caseId: 'case_003',
    claimType: 'Continuous Judicial Experience Duration',
    fieldLabel: 'Years of Unbroken Legal Practice',
    candidateDocumentValue: '18 Years Continuous (October 2007 - Present)',
    authoritativeSourceValue: '15 Years 9 Months (Interrupted: Inactive 2014-2016)',
    sourceName: 'Western Province Bar Disciplinary & Roll Register',
    evidenceLocation: 'Page 1, Clause 4',
    dateChecked: '2026-08-26 07:20 UTC',
    reliabilityTier: 'TIER_1_STATUTORY_AUTHORITY',
    status: 'CONTRADICTED',
    resolution: 'ESCALATED',
    resolutionNote: 'Requires senior adjudication review. Candidate asserts sabbatical while authoritative roll recorded voluntary inactive status.',
    resolvedBy: 'Marcus Chen (Senior Adjudicator)',
  },
  {
    id: 'disc_003',
    is_demo: true,
    caseId: 'case_006',
    claimType: 'Dual Citizenship Renunciation Attestation',
    fieldLabel: 'Foreign Citizenship Relinquishment Date',
    candidateDocumentValue: 'Relinquished March 14, 2024',
    authoritativeSourceValue: 'Foreign Consular Registry pending confirmation',
    sourceName: 'Consular & Diplomatic Records Service',
    evidenceLocation: 'Page 3, Foreign Consular Letter',
    dateChecked: '2026-08-25 14:00 UTC',
    reliabilityTier: 'TIER_2_OFFICIAL_REGISTRY',
    status: 'PENDING',
    resolution: 'UNRESOLVED',
    resolutionNote: 'Consular response pending bilateral treaty verification timeframe.',
  },
];

export const MOCK_AUDIT_LOGS: AuditLogEvent[] = [
  {
    id: 'aud_1001',
    is_demo: true,
    timestamp: '2026-08-26 11:20:14 UTC',
    actorId: 'usr_analyst_01',
    actorName: 'Elena Vance',
    actorRole: 'VERIFICATION_ANALYST',
    eventType: 'FIELD_VALUE_CORRECTED',
    summary: 'Corrected Extracted Field [Conferral Date] on Case CASE-2026-0019-JD',
    previousValue: '2002-05-18',
    newValue: '2002-06-12',
    reason: 'REGISTRAR_RECORDS_AMENDMENT - Adjusted to match authoritative NADC convocation register date.',
    caseReference: 'CASE-2026-0019-JD',
    technicalHash: 'sha256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
    severity: 'INFO',
  },
  {
    id: 'aud_1002',
    is_demo: true,
    timestamp: '2026-08-26 10:45:02 UTC',
    actorId: 'usr_intake_01',
    actorName: 'Amina Osei',
    actorRole: 'INTAKE_OFFICER',
    eventType: 'CANDIDATE_SUBMISSION_INTAKE',
    summary: 'Registered Candidate Submission [Clara Maria Villanueva-Cruz] for Constituency 7',
    previousValue: 'N/A (New Record)',
    newValue: 'Candidate Reference PAC-2026-0240 Created',
    reason: 'Statutory filing window submission intake verified and timestamped.',
    caseReference: 'CASE-2026-0240-NA',
    technicalHash: 'sha256:4a35b2e987c14a2f8b55e3a89012cd5e49201f893a7d4512e9b88a9c01476f11',
    severity: 'INFO',
  },
  {
    id: 'aud_1003',
    is_demo: true,
    timestamp: '2026-08-26 09:16:30 UTC',
    actorId: 'sys_connector_nadc',
    actorName: 'Verification Engine (NADC Connector)',
    actorRole: 'VERIFICATION_ANALYST',
    eventType: 'SOURCE_QUERY_COMPLETED',
    summary: 'Automated source check against National Academic Degree Clearinghouse',
    previousValue: 'Status: PENDING_QUERY',
    newValue: 'Status: VERIFIED (Response Code: 200 OK)',
    reason: 'Automated verification check performed.',
    caseReference: 'CASE-2026-0019-JD',
    technicalHash: 'sha256:8899aabbccddeeff00112233445566778899aabbccddeeff0011223344556677',
    severity: 'INFO',
  },
  {
    id: 'aud_1004',
    is_demo: true,
    timestamp: '2026-08-26 08:50:11 UTC',
    actorId: 'usr_adjudicator_01',
    actorName: 'Marcus Chen',
    actorRole: 'SENIOR_ADJUDICATOR',
    eventType: 'DISCREPANCY_FLAGGED',
    summary: 'Flagged Discrepancy #DISC-002 on Candidate Julian Robert Hawthorne',
    previousValue: 'Workflow Stage: ANALYSIS',
    newValue: 'Workflow Stage: ADJUDICATION (CONTRADICTED)',
    reason: 'Potential integrity concern: 27-month inactive period contradicts statutory continuous practice threshold.',
    caseReference: 'CASE-2026-0081-JC',
    technicalHash: 'sha256:9123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
    severity: 'WARNING',
  },
  {
    id: 'aud_1005',
    is_demo: true,
    timestamp: '2026-08-26 08:45:29 UTC',
    actorId: 'sys_connector_rev',
    actorName: 'Verification Engine (Revenue Gateway)',
    actorRole: 'VERIFICATION_ANALYST',
    eventType: 'CONNECTOR_EXCEPTION',
    summary: 'Source connectivity failure to Department of Revenue Gateway (HTTP 503 Timeout)',
    previousValue: 'Status: ONLINE',
    newValue: 'Status: OFFLINE / RETRY_QUEUED',
    reason: 'Upstream gateway socket timeout. Circuit breaker engaged.',
    caseReference: 'CASE-2026-0042-FD',
    technicalHash: 'sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    severity: 'CRITICAL',
  },
  {
    id: 'aud_1006',
    is_demo: true,
    timestamp: '2026-08-25 17:15:00 UTC',
    actorId: 'usr_analyst_01',
    actorName: 'Elena Vance',
    actorRole: 'VERIFICATION_ANALYST',
    eventType: 'RECOMMENDATION_RECORDED',
    summary: 'Recorded recommendation [Verification requirements satisfied] for Senator Fatima Al-Mansoor',
    previousValue: 'Status: IN_REVIEW',
    newValue: 'Recommendation: REQUIREMENTS_SATISFIED',
    reason: 'All statutory citizenship, identity, and degree criteria confirmed against Tier 1 sources.',
    caseReference: 'CASE-2026-0104-NA',
    technicalHash: 'sha256:ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb',
    severity: 'INFO',
  },
];

export const MOCK_RFIS: CandidateRFI[] = [
  {
    id: 'rfi_001',
    is_demo: true,
    rfiNumber: 'RFI-PAC-2026-0019-01',
    caseId: 'case_001',
    caseReference: 'PAC-2026-0019',
    candidateId: 'cand_001',
    candidateName: 'Dr. Arthur Sterling-Morales',
    statutoryBasis: 'Veridia Electoral Integrity Act § 19.3 & Judicial Appointments Rule 8',
    subject: 'Clarification of Degree Conferral Date vs. Archival Registry Records',
    discrepancyRef: 'Academic degree year discrepancy (1999 vs 2000 registry entry)',
    credentialType: 'ACADEMIC_DEGREE',
    instructions: 'Please provide either an official certified transcript duplicate or an explanatory affidavit from the Registrar of Veritasia State University reconciling the degree conferral commencement date.',
    curingRequirements: [
      'Certified duplicate transcript with Registrar embossed dry seal',
      'Affidavit of Name & Degree Conferral Date from Dean of Academic Records',
      'Proof of Bar Admission eligibility under degree title',
    ],
    issuedByStaffId: 'usr_analyst_01',
    issuedByName: 'Elena Vance (Verification Analyst)',
    issuedTimestamp: '2026-08-25 14:15',
    responseDeadline: '2026-08-29 17:00',
    status: 'RESPONSE_SUBMITTED',
    candidateResponseText: 'We have obtained an expedited letter from the Dean of Veritasia State University confirming that Dr. Sterling-Morales completed degree requirements in November 1999, but official university congregation convocation was formally recorded in June 2000. Certified institutional addendum attached.',
    candidateResponseTimestamp: '2026-08-26 09:45',
    submittedByAgentName: 'Marcus Vance, Legal Counsel for Candidate',
    attachments: [
      {
        id: 'att_01',
    is_demo: true,
        fileName: 'VSU_Registrar_Convocation_Addendum_1999_2000.pdf',
        fileSizeBytes: 842000,
        uploadedAt: '2026-08-26 09:45',
        description: 'Official letter from University Registrar clarifying convocation cycle vs completion date.',
        sha256Hash: 'sha256:4d8a1768fba2e98c91...',
      },
    ],
    adjudicationNote: '',
  },
  {
    id: 'rfi_002',
    is_demo: true,
    rfiNumber: 'RFI-PAC-2026-0182-01',
    caseId: 'case_002',
    caseReference: 'PAC-2026-0182',
    candidateId: 'cand_002',
    candidateName: 'Hon. Samantha Ross-Chen',
    statutoryBasis: 'Public Integrity Act § 22 & Electoral Regulations Part IV',
    subject: 'Supplementary Tax Integrity Gateway Clearance Certificate Request',
    discrepancyRef: 'Tax authority API gateway timeout / unconfirmed compliance token',
    credentialType: 'FINANCIAL_DISCLOSURE',
    instructions: 'Due to a temporary gateway outage with the Revenue Department database, please upload a hardcopy Tax Compliance Certificate issued within the last 60 calendar days with digital QR verification code.',
    curingRequirements: [
      'Current Year Tax Clearance Certificate with verified Taxpayer PIN',
      'Signed declaration of asset compliance Schedule D',
    ],
    issuedByStaffId: 'usr_analyst_01',
    issuedByName: 'Elena Vance (Verification Analyst)',
    issuedTimestamp: '2026-08-26 10:15',
    responseDeadline: '2026-08-30 17:00',
    status: 'ISSUED',
  },
];

export const MOCK_STATUTORY_RULES: StatutoryRule[] = [
  {
    id: 'rule_001',
    is_demo: true,
    ruleCode: 'STAT-BAR-EXP-15YR',
    name: 'Appellate Judicial Bar Standing Threshold (15 Years)',
    description: 'Candidates contesting Appellate Division Judge must have continuous active standing at the Supreme Judicial Bar for at least 15 years prior to election day.',
    targetOffice: 'Appellate Division Judge',
    credentialType: 'PROFESSIONAL_LICENSE',
    fieldKey: 'license_status',
    operator: 'CONTAINS',
    expectedValue: 'Active - In Good Standing',
    statutoryBasis: 'Judicial Appointments Act §8(2) & Const. Art. IV',
    severity: 'CRITICAL_DISQUALIFICATION',
    actionOnFail: 'AUTO_FLAG_DISCREPANCY',
    isActive: true,
    createdBy: 'Marcus Sterling (Senior Auditor)',
    createdAt: '2026-07-01 09:00',
  },
  {
    id: 'rule_002',
    is_demo: true,
    ruleCode: 'STAT-CIT-NATURAL-BORN',
    name: 'Statutory Citizenship by Birth or Naturalization > 10 Yrs',
    description: 'Validates that citizenship record explicitly categorizes candidate as citizen by birth or naturalized with certified civil registration.',
    targetOffice: 'ALL',
    credentialType: 'CITIZENSHIP',
    fieldKey: 'citizen_status',
    operator: 'CONTAINS',
    expectedValue: 'Citizen',
    statutoryBasis: 'Electoral Integrity Act §14(1)',
    severity: 'CRITICAL_DISQUALIFICATION',
    actionOnFail: 'BLOCK_RECOMMENDATION',
    isActive: true,
    createdBy: 'David Sterling (Admin)',
    createdAt: '2026-07-01 09:00',
  },
  {
    id: 'rule_003',
    is_demo: true,
    ruleCode: 'STAT-DEG-ACCREDITED-LAW',
    name: 'Accredited Juris Doctor / Bachelor of Laws Conferral',
    description: 'Requires candidate to possess verified JD, LLB, or LLM degree with student registry index number present.',
    targetOffice: 'Appellate Division Judge',
    credentialType: 'ACADEMIC_DEGREE',
    fieldKey: 'degree_title',
    operator: 'CONTAINS',
    expectedValue: 'Doctor of Jurisprudence',
    statutoryBasis: 'Judicial Appointments Act §8(1)',
    severity: 'MANDATORY_FLAG',
    actionOnFail: 'REQUIRE_AFFIDAVIT',
    isActive: true,
    createdBy: 'Elena Vance (Lead Analyst)',
    createdAt: '2026-07-15 11:30',
  },
  {
    id: 'rule_004',
    is_demo: true,
    ruleCode: 'STAT-FIN-SCHEDULE-REALTY',
    name: 'Asset & Liability Schedule D Real Property Full Disclosure',
    description: 'Mandatory declaration of beneficial property holdings and real estate valuation for high executive offices.',
    targetOffice: 'Governor of Capital Territory',
    credentialType: 'FINANCIAL_DISCLOSURE',
    fieldKey: 'schedule_d_real_property',
    operator: 'NOT_EMPTY',
    expectedValue: '',
    statutoryBasis: 'Public Integrity Act §22(4)',
    severity: 'MANDATORY_FLAG',
    actionOnFail: 'AUTO_FLAG_DISCREPANCY',
    isActive: true,
    createdBy: 'Amina Osei (Intake Officer)',
    createdAt: '2026-08-01 14:00',
  },
  {
    id: 'rule_005',
    is_demo: true,
    ruleCode: 'STAT-SEC-LEVEL3-CLEARANCE',
    name: 'National Police Non-Conviction Certificate Validity',
    description: 'Requires certificate issued within 90 days of candidate filing deadline with zero felony disqualifications.',
    targetOffice: 'ALL',
    credentialType: 'SECURITY_CLEARANCE',
    fieldKey: 'clearance_level',
    operator: 'NOT_EMPTY',
    expectedValue: '',
    statutoryBasis: 'Electoral Integrity Act §19',
    severity: 'ADVISORY_SCRUTINY',
    actionOnFail: 'ESCALATE_TO_CHAIR',
    isActive: true,
    createdBy: 'Elena Vance (Lead Analyst)',
    createdAt: '2026-08-10 16:45',
  },
];

export const MOCK_SYSTEM_CONFIG: SystemConfiguration = {
  version: '2.4.1',
  effectiveDate: '2026-07-01',
  lastModifiedBy: 'David Sterling (System Administrator)',
  approvalState: 'APPROVED',
  retentionDays: 730,
  slaTargetsHours: {
    URGENT: 24,
    HIGH: 72,
    MEDIUM: 120,
    STANDARD: 168,
  },
  elections: [
    { id: 'elec_2026_nat',
    is_demo: true, name: '2026 Pacifica National Assembly Election', date: '2026-11-03', jurisdiction: 'Pacifica National', active: true },
    { id: 'elec_2026_gov',
    is_demo: true, name: '2026 Capital Territory Gubernatorial Election', date: '2026-11-03', jurisdiction: 'Pacifica National', active: true },
    { id: 'elec_2026_jud',
    is_demo: true, name: '2026 Western Province Judicial Council', date: '2026-10-15', jurisdiction: 'Pacifica National', active: true },
  ],
  offices: [
    {
      id: 'off_mp',
    is_demo: true,
      title: 'Member of Parliament',
      electionId: 'elec_2026_nat',
      requiredCredentials: ['CITIZENSHIP', 'ACADEMIC_DEGREE', 'FINANCIAL_DISCLOSURE', 'SECURITY_CLEARANCE'],
    },
    {
      id: 'off_gov',
    is_demo: true,
      title: 'Governor of Capital Territory',
      electionId: 'elec_2026_gov',
      requiredCredentials: ['CITIZENSHIP', 'ACADEMIC_DEGREE', 'FINANCIAL_DISCLOSURE', 'SECURITY_CLEARANCE'],
    },
    {
      id: 'off_judge',
    is_demo: true,
      title: 'Appellate Division Judge',
      electionId: 'elec_2026_jud',
      requiredCredentials: ['CITIZENSHIP', 'ACADEMIC_DEGREE', 'PROFESSIONAL_LICENSE', 'FINANCIAL_DISCLOSURE', 'SECURITY_CLEARANCE'],
    },
  ],
  credentialTypes: [
    {
      type: 'CITIZENSHIP',
      name: 'Proof of Statutory Citizenship & Identity',
      statutoryBasis: 'Electoral Act §14(1) - Birth Right or Naturalization Registry Proof',
      mandatoryClaims: ['Full Legal Name', 'Date of Birth', 'Citizenship Status', 'Registry Reference'],
    },
    {
      type: 'ACADEMIC_DEGREE',
      name: 'Tertiary Academic Degree Qualification',
      statutoryBasis: 'Electoral Act §14(3) - Accredited Higher Education Baccalaureate or Post-Graduate Qualification',
      mandatoryClaims: ['Conferring Institution', 'Degree Title', 'Conferral Date', 'Student Registration Index'],
    },
    {
      type: 'PROFESSIONAL_LICENSE',
      name: 'Professional Bar & Ethical Licensure',
      statutoryBasis: 'Judicial Appointments Act §8(2) - Minimum 15 Years Continuous Good Standing at the Bar',
      mandatoryClaims: ['Licensing Authority', 'Roll Number', 'Current Ethical Standing', 'Admission Date'],
    },
    {
      type: 'FINANCIAL_DISCLOSURE',
      name: 'Public Integrity Asset & Liability Disclosure',
      statutoryBasis: 'Public Integrity Act §22 - Annual Financial Statement and Beneficial Ownership Declarations',
      mandatoryClaims: ['Filing Period', 'Schedule A Assets', 'Schedule B Liabilities', 'Schedule D Real Property'],
    },
    {
      type: 'SECURITY_CLEARANCE',
      name: 'Security Clearance & Non-Conviction Attestation',
      statutoryBasis: 'Electoral Integrity Act §19 - Certified National Police Record Attestation',
      mandatoryClaims: ['Clearance Level', 'Issuing Police Registry', 'Certificate Serial', 'Expiry Date'],
    },
  ],
  approvedAuthorities: [
    { name: 'National Academic Degree Clearinghouse (NADC)', tier: 'TIER_1_STATUTORY_AUTHORITY', endpointStatus: 'HEALTHY', lastPing: '30s ago' },
    { name: 'National Registry of Civil Status (NRCS)', tier: 'TIER_1_STATUTORY_AUTHORITY', endpointStatus: 'HEALTHY', lastPing: '15s ago' },
    { name: 'Supreme Judicial Bar of Pacifica Registry API', tier: 'TIER_1_STATUTORY_AUTHORITY', endpointStatus: 'HEALTHY', lastPing: '45s ago' },
    { name: 'National Police Criminal Records Registry (NPCRR)', tier: 'TIER_1_STATUTORY_AUTHORITY', endpointStatus: 'HEALTHY', lastPing: '1m ago' },
    { name: 'Department of Revenue Ethics & Disclosure Gateway', tier: 'TIER_1_STATUTORY_AUTHORITY', endpointStatus: 'OFFLINE', lastPing: '5m ago (Timeout)' },
    { name: 'National Archive Gateway & Identity Service', tier: 'TIER_2_OFFICIAL_REGISTRY', endpointStatus: 'DEGRADED', lastPing: '2m ago (Rate limited)' },
  ],
  reasonCodes: [
    { code: 'REGISTRAR_RECORDS_AMENDMENT', label: 'Registrar records show amended date or spelling', category: 'Correction' },
    { code: 'TRANSLITERATION_OR_TYPO', label: 'Diacritic, transliteration or typographical correction', category: 'Correction' },
    { code: 'LEGIBILITY_ENHANCEMENT', label: 'Field manually read from high-contrast review', category: 'Legibility' },
    { code: 'MANDATORY_CRITERIA_VERIFIED', label: 'All statutory prerequisites verified against primary source', category: 'Recommendation' },
    { code: 'MISSING_MANDATORY_ANNEXURE', label: 'Document omitted statutory required schedule or seal', category: 'Deficiency' },
    { code: 'STATUTORY_THRESHOLD_UNMET', label: 'Discrepancy in duration or standing requirement', category: 'Discrepancy' },
  ],
};
